server:
  port: 8003
  servlet:
    context-path: /batch

spring:
  datasource:
    url: jdbc:mysql://localhost/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: wxz123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.neilxu.train.batch.mapper: trace
